<?php
/**
 * Implements hook_uc_checkout_pane().
 * Used to add a pane to the checkout
 */
function uc_mailchimp_subscribe_uc_checkout_pane() {
  $panes['uc_mailchimp_subscribe'] = array(
    'callback' => 'uc_mailchimp_subscribe_checkout_pane_callback',
    'title' => t('Subscription Options'),
    'desc' => t("Allow customers to subscribe to MailChimp."),
    'weight' => 1,
    'process' => FALSE,
    'collapsible' => FALSE,
  );
  return $panes;
}

/**
 * Callback which process the user's subscription option
 */
function uc_mailchimp_subscribe_checkout_pane_callback($op, $order, $form = NULL, &$form_state = NULL) {
  switch ($op) {
    case 'view':
      $description = t('Would you like to subscribe to our newsletter?');
      $default = NULL;
      $contents['subscribe'] = array(
        '#type' => 'checkbox',
        '#title' => t('Yes please!'),
        '#default_value' => $default,
      );
      return array('description' => $description, 'contents' => $contents);

    case 'process':
      $order->data['subscribe'] = $form_state['input']['panes']['uc_mailchimp_subscribe']['subscribe'];
      
      

    case 'review':
    if ($order->data['subscribe'] == 1) {
      $review = NULL;
      $review[] = array('title' => t('Subscribe'), 'data' => 'Yes');
      return $review;
	}
  }
}

/**
 * Subscribes user to a list and adds an order admin comment.
 */
function uc_mailchimp_subscribe_to_list($account, $order) {
	require_once $_SERVER['DOCUMENT_ROOT'] . '/sites/all/libraries/mailchimp/MCAPI.class.php';
	
	// REPLACE THESE VALUES WITH YOUR OWN
	$apikey = '2c0816aa3a66abd6e9890d693a2a7b3e-us7';
	$listId = '1e3329cad6';
	 
	$api = new MCAPI($apikey);
	$merge_vars = array(
		'FNAME'=> $order->billing_first_name,
	);
	$retval = $api->listSubscribe($listId, $order->primary_email, $merge_vars);
	 
	// Debugging
/*
	if ($api->errorCode){
		drupal_set_message("\tCode=".$api->errorCode."\n"."\tMsg=".$api->errorMessage."\n");
	} 
	else {
	    drupal_set_message("Subscribed - look for the confirmation email!\n");
	}
*/
}

/**
 * Implementation of hook_uc_checkout_complete()
 * Used to subscribe the user if they have opted in
 */

function uc_mailchimp_subscribe_uc_checkout_complete($order, $account) {
	if ($order->data['subscribe'] == 1) {
		uc_mailchimp_subscribe_to_list($account, $order);
	}
}